In [1]:
import numpy as np
import pandas as pd

In [8]:
#header=0表示文件第一行是列名
df = pd.read_csv('input/round1_ijcai_18_train_20180301.txt', sep=' ', header=0)
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

<font color=blue>__Question 1__</font>

In [16]:
df_corr['is_trade'] = df_corr['is_trade'].apply(lambda x: abs(x))
df_corr = df_corr.sort_values(by="is_trade", ascending=False)
df_corr.head()

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,...,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
is_trade,-0.002158,-0.000168,-0.005311,-0.014622,-0.055895,0.037358,0.013972,0.006077,0.000255,0.008843,...,-0.009274,-0.012313,-0.003238,-0.000747,-0.017355,-0.000735,-0.015578,-0.016239,-0.016734,1.000000
item_price_level,-0.000380,0.026952,-0.098667,0.240088,1.000000,-0.029377,0.083133,0.134814,0.001559,0.008266,...,0.023965,0.011926,-0.008429,0.045727,0.341513,0.048414,0.100911,0.099274,0.228606,0.055895
item_sales_level,-0.000263,-0.015316,-0.060640,-0.028618,-0.029377,1.000000,0.853855,0.757697,0.002646,-0.002519,...,0.009675,-0.080792,0.012862,0.463273,0.170366,0.459293,-0.008801,-0.012572,0.097055,0.037358
shop_review_positive_rate,-0.000198,0.002110,-0.095923,0.007857,0.341513,0.170366,0.206513,0.220753,-0.001299,0.000530,...,0.007088,-0.031808,0.029416,0.168541,1.000000,0.166854,0.329895,0.322094,0.465756,0.017355
shop_score_description,-0.000013,-0.000138,-0.060349,-0.004456,0.228606,0.097055,0.126126,0.148225,0.000152,-0.003033,...,0.004154,-0.022656,0.022326,0.070605,0.465756,0.068930,0.938355,0.931128,1.000000,0.016734

<font color=black>*Therefore, Q1 Answer: item_price_level, item_sales_level and shop_review_positive_rate*</font>

<font color=blue>__Question 2__</font>

In [17]:
from datetime import timedelta, datetime

#df['readable_timestamp'] = pd.to_datetime(df['context_timestamp'], unit='s')
#df['readable_timestamp'] = df['readable_timestamp'].dt.strftime(date_format="%Y-%m-%d")
df['readable_timestamp'] = df['context_timestamp'].apply(lambda x: datetime.fromtimestamp(x).date())
df = df.sort_values(by="readable_timestamp")
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,readable_timestamp
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.00000,1.000000,1.00000,0,2018-09-17
42004,5313124543839938873,1702174480111817936,7908382889764677758;5755694407684602296,5131280576272319091;1210779090663804691;462193...,3801992748557162347,8774880668563049760,7,11,10,17,...,"6007511169620956394:1354874066266948599,432448...",101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17
42007,1905518497671778779,8660401174110210500,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,3801992748557162347,8774880668563049760,7,9,12,16,...,5755694407684602296:4324484723289924768;836752...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17
42010,5139312501283221516,3569662746492370033,7908382889764677758;5755694407684602296,5131280576272319091;4621934203383159480;885142...,3801992748557162347,8774880668563049760,7,11,12,17,...,5755694407684602296:5131280576272319091;790838...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17
42013,7873313289460927037,3569662746492370033,7908382889764677758;5755694407684602296,5131280576272319091;4621934203383159480;885142...,3801992748557162347,8774880668563049760,7,11,12,17,...,"5755694407684602296:8240392130342951699,432448...",101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17

In [18]:
alldays = df['readable_timestamp'].unique()
#alldays.datetime.date()
alldays

array([datetime.date(2018, 9, 17), datetime.date(2018, 9, 18),
       datetime.date(2018, 9, 19), datetime.date(2018, 9, 20),
       datetime.date(2018, 9, 21), datetime.date(2018, 9, 22),
       datetime.date(2018, 9, 23), datetime.date(2018, 9, 24)],
      dtype=object)

In [19]:
# In the past 3 days, we calculate:
df0 = pd.DataFrame({})
for end_day in alldays:
    start_day = end_day - timedelta(days=3)
    last3days = df[(df['readable_timestamp'] <= end_day) & (df['readable_timestamp'] >= start_day)]
    #total_clicks = last3days['is_trade'].count()
    #total_trades = last3days.groupby('item_id')['is_trade'].sum()
    # 历史转化率 =  历史交易数量/历史总点击数量, which is the mean()
    df_tradeRate = last3days.groupby('item_id').mean()[['is_trade']]
    df_tradeRate['readable_timestamp'] = pd.Series([end_day for i in range(df_tradeRate.shape[0])], index=df_tradeRate.index)
    df0 = pd.concat([df0, df_tradeRate], axis = 0)

df0['item_id'] = df0.index
df_tradeRate = df0.rename(columns={'is_trade':'trade_rate'})
df_tradeRate.shape

(60841, 3)

In [20]:
df_tradeRate.head()

                   trade_rate readable_timestamp            item_id
item_id
696490723789804      0.000000         2018-09-17    696490723789804
1097631460775571     0.000000         2018-09-17   1097631460775571
1637165183538885     0.000000         2018-09-17   1637165183538885
9393908124420502     0.000000         2018-09-17   9393908124420502
10102212873966760    0.153846         2018-09-17  10102212873966760

In [21]:
df = df.merge(df_tradeRate, on=['item_id', 'readable_timestamp'], how='left')
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,readable_timestamp,trade_rate
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,6765930309048922341,4,1.0,5002,1.00000,1.000000,1.00000,0,2018-09-17,0.0
1,5313124543839938873,1702174480111817936,7908382889764677758;5755694407684602296,5131280576272319091;1210779090663804691;462193...,3801992748557162347,8774880668563049760,7,11,10,17,...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17,0.0
2,1905518497671778779,8660401174110210500,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,3801992748557162347,8774880668563049760,7,9,12,16,...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17,0.0
3,5139312501283221516,3569662746492370033,7908382889764677758;5755694407684602296,5131280576272319091;4621934203383159480;885142...,3801992748557162347,8774880668563049760,7,11,12,17,...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17,0.0
4,7873313289460927037,3569662746492370033,7908382889764677758;5755694407684602296,5131280576272319091;4621934203383159480;885142...,3801992748557162347,8774880668563049760,7,11,12,17,...,101123793812656776,15,1.0,5012,0.97469,0.972376,0.98623,0,2018-09-17,0.0